DROP TABLE users IF EXISTS;

-- CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE users
(
    user_id     INTEGER generated by default as identity NOT NULL ,
    login       VARCHAR(32)            NOT NULL,
    email       VARCHAR(128)            NOT NULL,
    registered  TIMESTAMP DEFAULT now() NOT NULL,
    PRIMARY KEY (user_id)

);

INSERT INTO users (login, email) VALUES ('john123', 'john@example.com');