DROP TABLE users IF EXISTS;

-- CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE users
(
    id          INTEGER generated by default as identity NOT NULL ,
    user_id     INTEGER NOT NULL,
    login       VARCHAR(32)            NOT NULL,
    email       VARCHAR(128)            NOT NULL,
    registered  TIMESTAMP DEFAULT now() NOT NULL,
    PRIMARY KEY (id)

);

INSERT INTO users (user_id, login, email) values ( 25,'goravski','goravsky@tut.by' )